name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    continue-on-error: true  # ✅ This prevents the job from failing the entire workflow
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Print working directory
        run: pwd

      - name: Run Python Linter
        run: |
          echo "Linting Python files..."
          FOUND=$(find . -name "*.py")
          if [ -z "$FOUND" ]; then
            echo "No Python files found to lint."
          else
            echo "$FOUND" | xargs flake8 || echo "Some Python lint issues found."
          fi
        continue-on-error: true  # ✅ Prevent failing due to lint errors

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run JavaScript Linter
        run: |
          echo "Linting JavaScript files in ./server/database..."
          FOUND=$(find ./server/database -name "*.js" 2>/dev/null)
          if [ -z "$FOUND" ]; then
            echo "No JS files found in ./server/database."
          else
            echo "$FOUND" | xargs jshint || echo "Some JS lint issues found."
          fi
        continue-on-error: true
